### ISSUE TITLE
Colour accessibility

### ISSUE THREAD

**Issue by filipkilibarda** [ubcctf/ubcctf.github.io#15]
Lets talk about the colour scheme on our website. 

I think it's a cool theme, but we've had a complaint that it has accessibility issues. The complaint was about there being too many colours.

We'd have to decide on how to colour things like code blocks, inline code, links, etc. But as for the body text, maybe just white-ish would be a safe bet? No hues of blue or anything, just white.

Our links currently have a pretty low contrast score, so we should change that I think. We should aim for a score of 7 or 9 (chrome).

![image](https://user-images.githubusercontent.com/15305892/104377013-abfcb080-54da-11eb-9d0c-e0d6e9204cc8.png)

**Comment by filipkilibarda** [comment]
just messing around in devtools

![image](https://user-images.githubusercontent.com/15305892/104379264-18c57a00-54de-11eb-95a0-f42e3bacf599.png)

**Comment by jamiepoli** [comment]
Can we consider this issue resolved due to https://github.com/ubcctf/ubcctf.github.io/pull/13 ?
