### ISSUE TITLE
Broken navbar link on /challenge

### ISSUE THREAD

**Issue by Green-Avocado** [ubcctf/ubcctf.github.io#47]
On the https://ubcctf.github.io/challenge/ page, the navbar link to challenge points to https://ubcctf.github.io/%20challenge and returns a 404 error

**Comment by jamiepoli** [comment]
Thanks! Fixed in this [commit](https://github.com/ubcctf/ubcctf.github.io/commit/5a714c058fabc74de532f9439e8711ea46bf6049)
